name: "Commit Action"
description: "Commit Action"
inputs:
  github-token:
    description: "The GitHub Token"
    required: true
    default: "${{ github.token }}"
  base-branch:
    description: "The base branch"
    required: true
    default: "${{ github.ref_name }}"
  head-branch:
    description: "The head branch"
    required: false
  commit-message:
    description: "The commit message"
    required: false
  working-directory:
    description: "The working directory"
    required: false
    default: "."
outputs:
  commit-url:
    description: "The URL of a commit created"
    value: ${{ steps.commit.outputs.commit-url }}
runs:
  using: "composite"
  steps:
    - id: commit
      run: |
        cd 
        ${{ github.action_path }}/commit.sh
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        GITHUB_TOKEN: "${{ inputs.github-token }}"
        INPUT_BASE_BRANCH: "${{ inputs.base-branch }}"
        INPUT_HEAD_BRANCH: "${{ inputs.head-branch }}"
        INPUT_COMMIT_MESSAGE: "${{ inputs.commit-message }}"
