name: test
on:
  push:
    branches-ignore:
      - "actions-commit/*"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github-token: "this token should be not used because there is no changes"
      - name: make some changes
        run: ./testdata/update.sh
        shell: bash
      - id: commit
        uses: ./
        with:
          head-branch: "actions-commit/${{ github.run_id}}-${{ github.run_attempt }}"
